### PR TITLE
[chore] Update EKS-D latest image tags

### PR DESCRIPTION
**Pull request by premdass**
Updating latest image tags of EKS-D

Towards https://github.com/aws/eks-distro/issues/1174

Issue #, if available:
https://github.com/aws/eks-distro/issues/1174

Description of changes:
Updating the EKS-D image tags to latest

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

### CODE REVIEW

**Review by hakuna-matatah — APPROVED** [review]
lgtm

**Comment by premdass** [comment]
an somebody merge this when time permits pls ?

**Comment by mengqiy** [comment]
@premdass These tags are not publicly accessible, which is not expected, right?
This is problematic when using the operator built from HEAD.
I'd suggest 2 solutions going forward:
- Make those tags publicly accessible .
- Revert this change until those tag are ready.

**Comment by mengqiy** [comment]
KIT operator is broken on the HEAD of main. This should really be caught by our CI.

**Comment by mengqiy** [comment]
Looking at https://github.com/aws/eks-distro/issues/1174#issuecomment-1295638015, it appears we are not using the right image tags in this PR.

**Pull request merged**
